name = "LogicalOperators"
uuid = "6ac76662-4673-4d6a-8390-a82adc3670cf"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Jive"]

[compat]
Jive = "0.3"
